name: dym9.xyz

on:
  push:
    branches: [production]
  workflow_dispatch:

env:
  AWS_REGION: ap-southeast-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm dependencies
        uses: ./.github/actions/install-pnpm-dependencies

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build Website
        run: pnpm build
        env:
          VITE_STAGE: "production"
          VITE_DYM_ADDRESS: "0x80b5a32E4F032B2a058b4F29EC95EEfEEB87aDcd"
          VITE_CONTRACT_ADDRESS: "0x0E67684C8E0b002526D9d52492d49E983438537E"

      - name: Push data to S3
        run: aws s3 sync build/ s3://dym9.xyz/ --acl public-read
